# Generated by Django 6.0.6 on 2026-06-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'Accueil',
                'verbose_name_plural': 'Accueils',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('name_project', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom du Projet')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description du Projet')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image projet')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True, verbose_name='Profession ')),
                ('nom_societe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la société')),
                ('mission', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mission au sein de la société')),
            ],
            options={
                'verbose_name': 'Résumé',
                'verbose_name_plural': 'Résumés',
            },
        ),
    ]
